import os
import json
import re

PROBLEMS_JS_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), "problems_data.js")
PROBLEMS_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "problems")

def load_problems_data():
    if not os.path.exists(PROBLEMS_JS_PATH):
        return {}

    with open(PROBLEMS_JS_PATH, "r", encoding="utf-8") as f:
        content = f.read()

    match = re.search(r"const practiceData\s*=\s*(\{[\s\S]*\});?\s*$", content)
    if not match:
        return {}

    js_obj = match.group(1)
    try:
        return json.loads(js_obj)
    except json.JSONDecodeError:
        fixed = re.sub(r'(\w+)\s*:', r'"\1":', js_obj)
        try:
            return json.loads(fixed)
        except json.JSONDecodeError:
            return {}

def main():
    data = load_problems_data()
    if not data:
        print("No data found or parse failed.")
        return

    os.makedirs(PROBLEMS_DIR, exist_ok=True)
    available_paths = list(data.keys())

    # Write individual files
    for path, content in data.items():
        file_path = os.path.join(PROBLEMS_DIR, f"{path}.js")
        os.makedirs(os.path.dirname(file_path), exist_ok=True)
        
        json_str = json.dumps(content, ensure_ascii=False, indent=4)
        js_code = f"""// Auto-generated by migrate_problems.py
window.practiceData = window.practiceData || {{}};
window.practiceData["{path}"] = {json_str};
"""
        with open(file_path, "w", encoding="utf-8") as f:
            f.write(js_code)
        print(f"Created: {file_path}")

    # Write index.js
    index_path = os.path.join(PROBLEMS_DIR, "index.js")
    paths_json = json.dumps(available_paths, ensure_ascii=False, indent=4)
    index_code = f"""// Auto-generated by migrate_problems.py or generate_problems.py
const availablePracticePaths = {paths_json};
"""
    with open(index_path, "w", encoding="utf-8") as f:
        f.write(index_code)
    print(f"Created: {index_path}")

if __name__ == "__main__":
    main()
